# Hotel Reservation Predicton

In this project, we will create a model that will predict whether the customer will cancel the reservation of a hotel or keep it.

We are using this dataset from Kaggle : https://www.kaggle.com/datasets/ahsan81/hotel-reservations-classification-dataset

---

# Data Analysis

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("data/Hotel Reservations.csv")
df.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled

In [4]:
print(df.shape)
print(df.columns)

(36275, 19)
Index(['Booking_ID', 'no_of_adults', 'no_of_children', 'no_of_weekend_nights',
       'no_of_week_nights', 'type_of_meal_plan', 'required_car_parking_space',
       'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month',
       'arrival_date', 'market_segment_type', 'repeated_guest',
       'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
       'avg_price_per_room', 'no_of_special_requests', 'booking_status'],
      dtype='str')

Ok so, we have 36k rows and 19 columns. After looking at the columns, we wouldn't need Booking_ID. And there are different columns for arrival years, months and days. I don't see a use of these either. There is a column lead_time which is the number of days between the date of booking and the arrival date. This might be a factor affecting our result. But I don't see the use the y,m and d. So, I am gonna drop them too. And booking_status is our target column.

## Dropping Unnecessary Columns

In [6]:
df = df.drop(columns= ["Booking_ID", "arrival_year", "arrival_month", "arrival_date"])
df.head(2)

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,Offline,0,0,0,65.00,0,Not_Canceled
1,2,0,2,3,Not Selected,0,Room_Type 1,5,Online,0,0,0,106.68,1,Not_Canceled

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 15 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   no_of_adults                          36275 non-null  int64
 1   no_of_children                        36275 non-null  int64
 2   no_of_weekend_nights                  36275 non-null  int64
 3   no_of_week_nights                     36275 non-null  int64
 4   type_of_meal_plan                     36275 non-null  str
 5   required_car_parking_space            36275 non-null  int64
 6   room_type_reserved                    36275 non-null  str
 7   lead_time                             36275 non-null  int64
 8   market_segment_type                   36275 non-null  str
 9   repeated_guest                        36275 non-null  int64
 10  no_of_previous_cancellations          36275 non-null  int64
 11  no_of_previous_bookings_not_canceled  36275 non-null  int64
 12  avg_price_per_room                    36275 non-null  float64
 13  no_of_special_requests                36275 non-null  int64
 14  booking_status                        36275 non-null  str
dtypes: float64(1), int64(10), str(4)
memory usage: 4.2 MB

Let's analyze other columns.